framework:
    secret: '%env(APP_SECRET)%'
    annotations: true # Changed from false to true
    http_method_override: false
    handle_all_throwables: true
    default_locale: en
    translator:
        enabled: true
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - en
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        enabled: true
        storage_factory_id: session.storage.factory.native
        gc_maxlifetime: 3600
        gc_probability: 1
        gc_divisor: 100
    php_errors:
        log: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file