security:
  password_hashers:
    App\Entity\Utilisateur:
      algorithm: bcrypt
      cost: 12

  providers:
    app_user_provider:
      entity:
        class: App\Entity\Utilisateur
        property: email

  role_hierarchy:
    ROLE_ADMIN: [ROLE_USER]
    ROLE_COACH: [ROLE_USER]
    ROLE_CLIENT: [ROLE_USER]

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      lazy: true
      provider: app_user_provider
      form_login:
        login_path: app_login_page
        check_path: app_login
        default_target_path: app_home
        username_parameter: email
        password_parameter: password
        enable_csrf: true
        success_handler: App\Security\LoginSuccessHandler
        failure_handler: App\Security\LoginFailureHandler
      logout:
        path: app_logout
        target: app_login_page

  access_control:
    - { path: ^/register, roles: PUBLIC_ACCESS }
    - { path: ^/login, roles: PUBLIC_ACCESS }
    - { path: ^/mot-passe-oublie, roles: PUBLIC_ACCESS }
    - { path: ^/verifier-code, roles: PUBLIC_ACCESS }
    - { path: ^/check-otp, roles: PUBLIC_ACCESS }
    - { path: ^/reset-password, roles: PUBLIC_ACCESS } # Optional, if you use it
    - { path: ^/admin, roles: ROLE_ADMIN }
    - { path: ^/coach, roles: ROLE_COACH }
    - { path: ^/home, roles: [ROLE_CLIENT, ROLE_ADMIN, ROLE_COACH] }
    - { path: ^/$, roles: PUBLIC_ACCESS }
    - { path: ^/, roles: [ROLE_CLIENT, ROLE_COACH, ROLE_ADMIN] }
    - { path: ^/reset-password, roles: PUBLIC_ACCESS }

