version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    environment:
      - DATABASE_URL=mysql://root:@host.docker.internal:3306/esports?serverVersion=8.0.31&charset=utf8mb4
    depends_on:
      - db
    networks:
      - symfony-network

  db:
    image: mysql:8.0
    platform: linux/x86_64
    environment:
      MYSQL_DATABASE: esports
      MYSQL_ROOT_PASSWORD: 
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - symfony-network

networks:
  symfony-network:
    driver: bridge

volumes:
  db-data: