version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    environment:
      - DATABASE_URL=mysql://root:@host.docker.internal:3306/symfony_app?serverVersion=8.0.31&charset=utf8mb4
    networks:
      - symfony-network

networks:
  symfony-network:
    driver: bridge