controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
forum_stats_dashboard:
    path: /admin/forum/stats
    controller: App\Controller\ForumStatsController::index
    methods: GET

api_forum_stats:
    path: /api/forum/stats
    controller: App\Controller\ForumStatsController::getStats
    methods: GET