# config/services.yaml

# Default configuration for services in *this* file
services:
    # Default configuration applies to all services defined below
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # Makes classes in src/ available to be used as services
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Explicitly define the CommentController service with its arguments
    App\Controller\CommentController:
        arguments:
            $logger: '@Psr\Log\LoggerInterface'
            $httpClient: '@Symfony\Contracts\HttpClient\HttpClientInterface'
            $sightengineApiUser: '%env(SIGHTENGINE_API_USER)%'
            $sightengineApiSecret: '%env(SIGHTENGINE_API_SECRET)%'

# Parameters should be defined after services if they’re only used there, but here it’s fine as is
parameters:
    uploads_directory: 'C:\xampp\htdocs\img\games'
    sightengine_api_user: '%env(SIGHTENGINE_API_USER)%'
    sightengine_api_secret: '%env(SIGHTENGINE_API_SECRET)%'