# config/services.yaml
parameters:
    #uploads_directory: 'C:\xampp\htdocs\uploads'
    dossier_upload: '%env(UPLOAD_DIR)%'
    image_base_url: '%env(IMAGE_BASE_URL)%'
    uploads_directory: '%env(UPLOAD_DIR)%'
    uploads_directory2: '%env(UPLOAD_DIR)%'
    cv_directory: '%env(UPLOAD_DIR)%'
    git_url: 'https://feresad.github.io/event-qr-code/'
    sightengine_api_user: '%env(SIGHTENGINE_API_USER)%'
    sightengine_api_secret: '%env(SIGHTENGINE_API_SECRET)%'
    gemini.api_key: 'AIzaSyCjjlK6kTJXy8Kevcl8xoO0KhvZesakw3g'
    stripe_secret_key: '%env(STRIPE_SECRET_KEY)%'
    stripe_public_key: '%env(STRIPE_PUBLIC_KEY)%'
    stripe.public_key: '%env(STRIPE_PUBLIC_KEY)%'
    imgbb_api_key: '%env(IMGBB_API_KEY)%'
    
services:
    App\Service\TopicRecommendationService:
    App\Service\TopicSubscriptionService:
    App\Controller\ForumController:
    App\Service\RedditService:
        arguments:
            $session: '@session'
            $params: '%kernel.parameters%'
            $logger: '@monolog.logger'
            $entityManager: '@doctrine.orm.entity_manager'
            $router: '@router'
            $questionsRepository: '@App\Repository\QuestionsRepository'
            $commentaireRepository: '@App\Repository\CommentaireRepository'
            $request: '@request_stack'
    
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
    
    App\Controller\StockController:
        arguments:
            $dossierUpload: '%dossierUpload%'  # Injection du paramètre
    App\Service\GeminiService:
        arguments:
            $apiKey: '%env(GEMINI_API_KEY)%'
    App\Controller\CommentController:
        arguments:
            $logger: '@Psr\Log\LoggerInterface'
            $httpClient: '@Symfony\Contracts\HttpClient\HttpClientInterface'
            $sightengineApiUser: '%env(SIGHTENGINE_API_USER)%'
            $sightengineApiSecret: '%env(SIGHTENGINE_API_SECRET)%'
     # Activer l'injection de paramètres si nécessaire
    Symfony\Component\HttpKernel\KernelInterface: '@kernel'

    App\Service\HardwareSpecsService:
        public: true

    App\Service\SystemSpecsService:
        public: true

    App\Service\GeminiFpsService:
        arguments:
            $apiKey: '%gemini.api_key%'
    App\Controller\PaymentController:
        arguments:
            $logger: '@monolog.logger'
    App\Controller\ForumStatsController:
        arguments:
            $logger: '@logger'
    App\EventSubscriber\CalendarSubscriber:
        arguments:
            $evenementRepository: '@App\Repository\EvenementRepository'
            $clientEvenementRepository: '@App\Repository\ClientEvenementRepository'
            $security: '@security.helper'
        tags:
            - { name: kernel.event_subscriber }
    App\EventListener\ExceptionListener:
        arguments:
            $twig: '@twig'
        tags:
            - { name: kernel.event_listener, event: kernel.exception, priority: 10 }