# config/services.yaml
parameters:
    #uploads_directory: 'C:\xampp\htdocs\uploads'
    uploads_directory: 'C:\xampp\htdocs\img\games'
    image_base_url: 'http://localhost/img/'
    git_url: 'https://feresad.github.io/event-qr-code/'
    sightengine_api_user: '%env(SIGHTENGINE_API_USER)%'
    sightengine_api_secret: '%env(SIGHTENGINE_API_SECRET)%'
services:
    App\Controller\ForumController:
    App\Service\RedditService:
        arguments:
            $session: '@session'
            $params: '%kernel.parameters%'
            $logger: '@monolog.logger'
    
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
    App\Service\ChatGPTService:
        arguments:
            $apiKey: '%env(OPENAI_API_KEY)%'
    App\Controller\CommentController:
        arguments:
            $logger: '@Psr\Log\LoggerInterface'
            $httpClient: '@Symfony\Contracts\HttpClient\HttpClientInterface'
            $sightengineApiUser: '%env(SIGHTENGINE_API_USER)%'
            $sightengineApiSecret: '%env(SIGHTENGINE_API_SECRET)%'