parameters:
    dossier_upload_ctr: '%kernel.project_dir%/public/uploads/'
    dossier_upload: '%kernel.project_dir%/public/uploads/'
    image_base_url: '/uploads/'  # Relative URL for static files on Render
    image_base_url2: '/uploads/'
    uploads_directory: '%kernel.project_dir%/public/uploads/'
    uploads_directory2: '%kernel.project_dir%/public/uploads/'
    git_url: 'https://feresad.github.io/event-qr-code/'
    sightengine_api_user: '%env(SIGHTENGINE_API_USER)%'
    sightengine_api_secret: '%env(SIGHTENGINE_API_SECRET)%'
    gemini.api_key: 'AIzaSyCjjlK6kTJXy8Kevcl8xoO0KhvZesakw3g'
    stripe_secret_key: '%env(STRIPE_SECRET_KEY)%'
    stripe_public_key: '%env(STRIPE_PUBLIC_KEY)%'
    stripe.public_key: '%env(STRIPE_PUBLIC_KEY)%'
    imgbb_api_key: '%env(IMGBB_API_KEY)%'
    cv_directory: '%kernel.project_dir%/public/uploads/'
    reddit_client_id: '%env(REDDIT_CLIENT_ID)%'
    reddit_client_secret: '%env(REDDIT_CLIENT_SECRET)%'
    reddit_user_agent: 'GoodGames-App/1.0 (by /u/YourRedditUsername)'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Repository\:
        resource: '../src/Repository/'
        public: true

    App\Controller\StockController:
        arguments:
            $dossierUpload: '%dossier_upload%'
        public: true

    App\Service\TopicRecommendationService:
    App\Service\TopicSubscriptionService:
    App\Controller\ForumController:
        arguments:
            $logger: '@monolog.logger'
            $subscriptionService: '@App\Service\TopicSubscriptionService'
            $translator: '@translator'
        public: true
    App\Service\RedditService:
        arguments:
            $httpClient: '@Symfony\Contracts\HttpClient\HttpClientInterface'
            $logger: '@monolog.logger'
            $clientId: '%env(REDDIT_CLIENT_ID)%'
            $clientSecret: '%env(REDDIT_CLIENT_SECRET)%'
            $userAgent: '%reddit_user_agent%'
        public: true
    App\Service\GeminiService:
        arguments:
            $apiKey: '%env(GEMINI_API_KEY)%'
    App\Controller\CommentController:
        arguments:
            $logger: '@Psr\Log\LoggerInterface'
            $httpClient: '@Symfony\Contracts\HttpClient\HttpClientInterface'
            $sightengineApiUser: '%env(SIGHTENGINE_API_USER)%'
            $sightengineApiSecret: '%env(SIGHTENGINE_API_SECRET)%'
    Symfony\Component\HttpKernel\KernelInterface: '@kernel'

    App\Service\HardwareSpecsService:
        public: true

    App\Service\SystemSpecsService:
        public: true

    App\Service\GeminiFpsService:
        arguments:
            $apiKey: '%gemini.api_key%'
    App\Controller\PaymentController:
        arguments:
            $logger: '@monolog.logger'
    App\Controller\ForumStatsController:
        arguments:
            $logger: '@logger'
    App\EventSubscriber\CalendarSubscriber:
        arguments:
            $evenementRepository: '@App\Repository\EvenementRepository'
            $clientEvenementRepository: '@App\Repository\ClientEvenementRepository'
            $security: '@security.helper'
        tags:
            - { name: kernel.event_subscriber }
    App\EventListener\ExceptionListener:
        arguments:
            $twig: '@twig'
        tags:
            - { name: kernel.event_listener, event: kernel.exception, priority: 10 }